apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: 172.27.186.119:4510/auth:369dbf175df23f9a061e09153c57b41d81e2b2e5
        ports:
        - containerPort: 8080
        env:
          - name: SPRING_DATASOURCE_URL
            value: "jdbc:postgresql://db:5432/postgres"
          - name: SPRING_DATASOURCE_USERNAME
            value: "postgres"
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: JWT_SECRET
          - name: SPRING_DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth-secrets
                key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: apps
spec:
  selector:
    app: auth
  ports:
  - port: 80
    targetPort: 8080
