apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: 172.27.186.119:4510/auth:v1.0.0
        ports:
        - containerPort: 8080
        env:
          - name: JWT_SECRET
            value: "R2FqU2h1ZDQzMWZsa2phc2RmcmtyYWZnYWtqM2FqazNsZmtqMw=="
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: apps
spec:
  selector:
    app: auth
  ports:
  - port: 80
    targetPort: 8080
